class Event:
    def __init__(self, transaction, type):
        self.transaction = transaction
        self.type = type


class EventType:
    E0_ENTERED_STATE = "ENTERED_STATE"
    E1_SEND_FILE_DATA = "SEND_FILE_DATA"
    E2_ABANDON_TRANSACTION = "ABANDON_TRANSACTION"
    E3_NOTICE_OF_CANCELLATION = "NOTICE_OF_CANCELLATION"
    E4_NOTICE_OF_SUSPENSION = "NOTICE_OF_SUSPENSION"
    E5_SUSPEND_TIMERS = "SUSPEND_TIMERS"
    E6_RESUME_TIMERS = "RESUME_TIMERS"

    E10_RECEIVED_METADATA = "RECEIVED_METADATA"
    E11_RECEIVED_FILEDATA = "RECEIVED_FILEDATA"
    E12_RECEIVED_EOF_NO_ERROR = "RECEIVED_EOF_NO_ERROR"
    E13_RECEIVED_EOF_CANCEL = "RECEIVED_EOF_CANCEL"
    E14_RECEIVED_ACK_EOF = "RECEIVED_ACK_EOF"
    E15_RECEIVED_NAK = "RECEIVED_NAK"
    E16_RECEIVED_FINISHED_NO_ERROR = "RECEIVED_FINISHED_NO_ERROR"
    E17_RECEIVED_FINISHED_CANCEL = "RECEIVED_FINISHED_CANCEL"
    E18_RECEIVED_ACK_FINISHED = "RECEIVED_ACK_FINISHED"

    E25_ACK_TIMEOUT = "ACK_TIMEOUT"
    E26_NAK_TIMEOUT = "NAK_TIMEOUT"
    E27_INACTIVITY_TIMEOUT = "INACTIVITY_TIMEOUT"

    E30_RECEIVED_PUT_REQUEST = "RECEIVED_PUT_REQUEST"
    E31_RECEIVED_SUSPEND_REQUEST = "RECEIVED_SUSPEND_REQUEST"
    E32_RECEIVED_RESUME_REQUEST = "RECEIVED_RESUME_REQUEST"
    E33_RECEIVED_CANCEL_REQUEST = "RECEIVED_CANCEL_REQUEST"
    E34_RECEIVED_REPORT_REQUEST = "RECEIVED_REPORT_REQUEST"

    E40_RECEIVED_FREEZE = "RECEIVED_FREEZE"
    E41_RECEIVED_THAW = "RECEIVED_THAW"
