configName: sam_v71_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../Harmony3
processor: ATSAMV71Q21B
projectName: ''
settings:
  PackageFilter: bootloader;bootloader_apps_uart;bsp;core;core_apps_sam_e70_s70_v70_v71;crypto;csp;csp_apps_sam_e70_s70_v70_v71;dev_packs;gfx;gfx_apps_sam_e70_s70_v70_v71;harmony-services;mc_apps_sam_e7x_s7x_v7x;motor_control;net;net_apps_sam_e70_v71;quick_docs;touch;usb;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAMV71_DFP\4.6.90\samv71b\atdf\ATSAMV71Q21B.atdf
